.\" Manpage for co2monitor-service


.TH co2monitor-service 1 "August 14, 2016" "0.0.5" "co2monitor-service man page"


.SH NAME

co2monitor-service \- a program to log co2 data from appropriate USB devices.


.SH SYNOPSIS

.B co2monitor-service
.\".RI [ OPTION ]


.SH DESCRIPTION

.B co2monitor-service 
logs data from co2 measuring devices with USB id 04d9:a052.

.SH OPTIONS

.B co2monitor-service

.\".TP
.\".B \-v
.\"Output version number and quit.


.SH AUTHOR
.B co2monitor-service
was written by Yann Büchau <yann.buechau@web.de>.
