.\" Manpage for co2monitor


.TH co2monitor 1 "August 14, 2016" "0.0.6" "co2monitor package man page"


.SH NAME

co2monitor \- a package for automatic co2 data logging from appropriate 
USB devices.


.SH DESCRIPTION

.B co2monitor 
logs data from co2 measuring devices with USB id 04d9:a052.

.SH EXECUTABLES

.TP
\fBco2monitor-service(1)
the logging service
.TP
\fBco2monitor-applet(1)
the monitoring applet (currently unfunctional)

.SH SEE ALSO

co2monitor-service(1), co2monitor-applet(1)

.SH AUTHOR
.B co2monitor
was written by Yann Buechau <yann.buechau@web.de>.
