#!/bin/sh -e
# remove __pycache__ folder before removing package
# otherwise dpkg complains about non-empty /usr/lib/co2monitor directory.
# Maybe there is a more elegant way to solve this...
for file in $(find usr -type d -iname '__pycache__');do
    rm -rf $file
done
