#!/bin/sh -e
# remove __pycache__ folder before removing package
# otherwise dpkg complains about non-empty /usr/lib/co2monitor directory.
# Maybe there is a more elegant way to solve this...
if [ -e /usr/lib/co2monitor/__pycache__ ];then
    rm -r /usr/lib/co2monitor/__pycache__
fi
